export { default as logo } from './logo.svg'
export { default as logotype } from './logotype.svg'
export { default as orangeCrystalPart } from './orange-crystal-part.svg'
export { default as pinkCrystalPart } from './pink-crystal-part.svg'
export { default as greenCrystalPart } from './green-crystal-part.svg'
export { default as orangeCrystalBg } from './orange-crystal-bg.svg'
export { default as pinkCrystalBg } from './pink-crystal-bg.svg'
export { default as greenCrystalBg } from './green-crystal-bg.svg'
export { default as orangeBg } from './orange-bg.svg'
export { default as pinkBg } from './pink-bg.svg'
export { default as greenBg } from './green-bg.svg'
export { default as nabatImage } from './nabat-image.svg'
export { default as darkCreamBg } from '../dark cream BG.svg'
export { default as navbarBg } from '../Navbar BG.svg'
export { default as heroImage } from '../Hero image.svg'
